# 深度学习初窥之神经网络模型

## 单层神经网络

神经网络模型其实是在模仿人类大脑思考方式。神经元是神经系统最基本的结构，分为突起和细胞体两部分。人类大脑在思考时，神经元会接收外部的刺激，当传入的冲动使神经元的电位超过阈值时，神经元就从抑制状态转向兴奋，并将信号向下一个神经元传递。神经网络模型的思想就是通过构造人造神经元的方式模拟这一过程。

![](./3-单层神经网络.png)

如上图所示，在一个简单的神经网络模型中有两组神经元，一组接收信号，一组输出信号。接收信号的一组神经元通过线性变换和非线性的激活函数转换来修改信号，并传递给下一组神经元。上图描述的就是大脑，基本工作模式。

## 激活函数

### Relu激活函数

如下图所示，Relu函数是一种分段线性函数，当输入为正数时，输入多少输出多少；当输入为负数时，输出为0。

![](./4-Relu分段线性函数.png)

### 其他激活函数见博客

[代码点亮人生](https://blog.csdn.net/Soft_Po/article/details/123382285)

## 多层神经网络

在实际应用中，神经网络模型往往不是单层的，而是如下图所示的多层神经网络模型（正如大脑的结构）。在多层神经网络模型中，输入层和输出层之间可以有多个隐含层，层与层之间连接，信号不断地从上一层传递到下一层，最后由输出层输出。这样，就可以处理复杂问题了！这正是深度学习中“深度”的由来！

![](./1-MPL.png)

# 神经网络模型简单代码实现

## 神经网络分类模型：MLPClassifier

In [1]:
from sklearn.neural_network import MLPClassifier
import pandas as pd

X = [[1, 0], [5, 1], [6, 4], [4, 2], [3, 2]]
y = [0, 1, 1, 0, 0]

# multi layer perceptron（感知机---单层神经网络）
mlp = MLPClassifier(hidden_layer_sizes=(100,50,30),max_iter=1000)

mlp.fit(X, y)
y_pred = mlp.predict(X)

result = pd.DataFrame()  # 创建一个空DataFrame 
result['预测值'] = list(y_pred)
result['实际值'] = list(y)
result

预测值  实际值
0    0    0
1    1    1
2    1    1
3    0    0
4    0    0

## 神经网络回归模型：MLPRegressor

In [6]:
from sklearn.neural_network import MLPRegressor
X = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]
y = [1, 2, 3, 4, 5]

# 设置random_state随机状态参数，使得每次训练的模型都是一样的
model = MLPRegressor()  
model.fit(X, y)

print(model.predict([[5, 5]]))

[2.89074279]


In [7]:
import numpy as np

In [15]:
rs = np.random.RandomState(seed = 1)
rs.randint(0,100,size = 1)

array([37])

# 用户评论情感分析

## 数据读取

In [3]:
import pandas as pd
data = pd.read_excel('产品评价.xlsx')
display(data.head(),data.shape)

客户编号                                                 评论  评价
0     1  是iPhone8 XR正品，按键屏幕反应蛮快的很灵活，屏幕6.0的不算很大，刚刚好，这款面容...   1
1     2  外形外观：外光非常漂亮，黑色的非常大气。适合男士拥有。屏幕音效：刚开机就下载了一个QQ音乐试...   1
2     3  从苹果4s，到6s，再到xr，就是喜欢苹果的手感和风格，视频流畅，图片清晰，纠结了好久买哪个...   1
3     4  主要是手感，太沉了，比苹果6，沉一倍，厚太多了，看中双卡双待机，刚买回来用，待机时间还不错，...   1
4     5  外形外观：红色超级好看，送妈妈的。屏幕音效：音效还可以，也什么特别的，屏幕看着也挺舒服。拍照...   1

(1080, 3)

## 中文分词

In [2]:
# jieba库分词示例 pip install jieba
import jieba
words = jieba.cut('我爱北京天安门')
for i in words:
    print(i)

Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\aa\AppData\Local\Temp\jieba.cache
Loading model cost 0.751 seconds.
Prefix dict has been built successfully.


我
爱
北京
天安门


In [6]:
# 这里先演示第一条评论的分词效果
import jieba
words = jieba.cut(data.iloc[1]['评论'])
print([w for w in words])
# result = ' '.join(words)
# print(result)

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\aa\AppData\Local\Temp\jieba.cache
Loading model cost 0.568 seconds.
Prefix dict has been built successfully.


['外形', '外观', '：', '外光', '非常', '漂亮', '，', '黑色', '的', '非常', '大气', '。', '适合', '男士', '拥有', '。', '屏幕', '音效', '：', '刚', '开机', '就', '下载', '了', '一个', 'QQ', '音乐', '试', '了', '一下', '。', ' ', '音效', '还是', '非常', '不错', '的', '。', '拍照', '效果', '：', '拍照', '很', '清晰', '，', '照亮', '你', '脸上', '的', '痘痘', '。', '运行', '速度', '：', '运行', '速度', '就', '不用说', '了', '。', ' ', '一个', '字快', '。', '待机时间', '：', '待机', '很', '不错', '。', '用', '一段时间', '再', '来', '评价', '。', '其他', '特色', '：', '个人感觉', '比', 'Ｘ', '好', '。', ' ', '可能', '是因为', '上手', '的', '手感', '比较', '好', '吧', '，', '总之', '还是', '值得', '入手', '的']


In [7]:
# 遍历整张表格，对所有评论进行分词
words = []
for i, row in data.iterrows():
    word = jieba.cut(row['评论'])
    result = ' '.join(word) 
    words.append(result)

In [23]:
words[:3]

['是 iPhone8   XR 正品 ， 按键 屏幕 反应 蛮快 的 很 灵活 ， 屏幕 6.0 的 不算 很大 ， 刚刚 好 ， 这 款 面容 识别 开锁 比 指纹 方便 多 了 ， 内外 的 整体 看起来 很 美观 ， 整机 子 不算 是 很厚感 ， 像素 高 比较 清晰 ， 双卡 双待 ， 续航 强 ， 跟 8plus 差价 300 元 ， 还是 选 XR 款好 ， 性能 不错 ， 处理器 、 芯片 也 是 最新 一代',
 '外形 外观 ： 外光 非常 漂亮 ， 黑色 的 非常 大气 。 适合 男士 拥有 。 屏幕 音效 ： 刚 开机 就 下载 了 一个 QQ 音乐 试 了 一下 。   音效 还是 非常 不错 的 。 拍照 效果 ： 拍照 很 清晰 ， 照亮 你 脸上 的 痘痘 。 运行 速度 ： 运行 速度 就 不用说 了 。   一个 字快 。 待机时间 ： 待机 很 不错 。 用 一段时间 再 来 评价 。 其他 特色 ： 个人感觉 比 Ｘ 好 。   可能 是因为 上手 的 手感 比较 好 吧 ， 总之 还是 值得 入手 的',
 '从 苹果 4s ， 到 6s ， 再 到 xr ， 就是 喜欢 苹果 的 手感 和 风格 ， 视频 流畅 ， 图片 清晰 ， 纠结 了 好久 买 哪个 颜色 ， 白色 干净 ， 同事 买 的 黄色 ， 感觉 也 很 好看 ， 蓝色 ， 珊瑚 我 也 喜欢 ， 最终 还是 选择 比较 适合 女生 的 珊瑚 色 ， 实物 比 图片 更 漂亮 ， 超级 喜欢 ， 运行 速度 快 ， 全屏 显示 ， 体积小 了 ， 可 显示 区域 变得 了 ， 很棒 。']

In [27]:
words.__len__()

1080

## 文本向量化

In [28]:
# 文本向量化CountVectorizer()函数的使用技巧：使用示例
from sklearn.feature_extraction.text import CountVectorizer
test = ['手机 外观 亮瞎眼 电视 外观 漂亮', '电脑 速度 YYDS ']

vect = CountVectorizer()
# stat
X = vect.fit_transform(test)
print(X)

X = X.toarray()
display(X)

words_bag = vect.vocabulary_
print(words_bag)

  (0, 3)	1
  (0, 2)	2
  (0, 1)	1
  (0, 6)	1
  (0, 4)	1
  (1, 5)	1
  (1, 7)	1
  (1, 0)	1


array([[0, 1, 2, 1, 1, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 0, 1]], dtype=int64)

{'手机': 3, '外观': 2, '亮瞎眼': 1, '电视': 6, '漂亮': 4, '电脑': 5, '速度': 7, 'yyds': 0}


In [8]:
# 实际应用
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer()
X = vect.fit_transform(words)

X = X.toarray()
print(X) # 每个数据长度是4075，字典的长度；出现了一个次，标记为1，出现了两次，标记为2，没有出现标记0
X.shape

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


(1080, 4075)

In [30]:
words_bag = vect.vocabulary_
from pprint import pprint
pprint(words_bag)

{'00': 0,
 '0022': 1,
 '0k': 2,
 '10': 3,
 '100': 4,
 '1000': 5,
 '10050': 6,
 '1080': 7,
 '1080p': 8,
 '10w': 9,
 '11': 10,
 '12': 11,
 '1200': 12,
 '128': 13,
 '1289': 14,
 '128g': 15,
 '128g5700': 16,
 '128gb': 17,
 '128gg': 18,
 '12w': 19,
 '13': 20,
 '14': 21,
 '15': 22,
 '16': 23,
 '16g': 24,
 '17': 25,
 '1792x828': 26,
 '18': 27,
 '18g': 28,
 '18w': 29,
 '19': 30,
 '1900': 31,
 '20': 32,
 '200': 33,
 '2014': 34,
 '2016': 35,
 '2018': 36,
 '2019': 37,
 '21': 38,
 '2108': 39,
 '23': 40,
 '24': 41,
 '25': 42,
 '256': 43,
 '256g': 44,
 '26': 45,
 '28': 46,
 '2900': 47,
 '298': 48,
 '30': 49,
 '300': 50,
 '3000': 51,
 '30pro': 52,
 '32': 53,
 '324ppi': 54,
 '33': 55,
 '35': 56,
 '35w': 57,
 '365': 58,
 '37': 59,
 '3799': 60,
 '3d': 61,
 '3dtouch': 62,
 '40': 63,
 '400': 64,
 '4399': 65,
 '4499': 66,
 '458': 67,
 '458ppi': 68,
 '460': 69,
 '4699': 70,
 '4780': 71,
 '4799': 72,
 '4800': 73,
 '4850': 74,
 '4888': 75,
 '4899': 76,
 '4980': 77,
 '4999': 78,
 '4g': 79,
 '4k': 80,
 '4s': 81

In [31]:
len(words_bag) # 样本匮乏，导致模型不够稳定

4075

## 目标变量提取

In [9]:
y = data['评价']
print(y.head())
y.shape

0    1
1    1
2    1
3    1
4    1
Name: 评价, dtype: int64


(1080,)

## 神经网络模型的搭建与使用

In [21]:
# %%time
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=1)

from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(64,64,32))

mlp.fit(X_train, y_train)
y_pred = mlp.predict(X_test)
print(y_pred)

[1 0 1 1 0 1 1 1 1 1 0 1 1 0 0 1 0 1 1 1 0 1 0 1 1 1 0 1 0 1 1 0 0 1 0 1 0
 1 1 0 1 0 0 1 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 0 1
 1 1 1 0 1 0 1 0 1 0 0 1 1 0 1 1 1 1 0 1 1 1 0 0 1 1 1 1 0 1 0 0 1 1]
CPU times: total: 17.2 s
Wall time: 3.43 s


In [11]:
result = pd.DataFrame()  # 创建一个空DataFrame 
result['预测值'] = list(y_pred)
result['实际值'] = list(y_test)
result

预测值  实际值
0      1    1
1      0    0
2      1    1
3      1    1
4      0    0
..   ...  ...
103    1    1
104    0    0
105    0    0
106    1    1
107    1    1

[108 rows x 2 columns]

## 准确率与应用

In [22]:
# 获取预测准确度
from sklearn.metrics import accuracy_score
score = accuracy_score(y_pred, y_test)
print('------------',score)

# 通过模型自带的score()函数也可以获取预测准确度
mlp.score(X_test, y_test)

------------ 0.9907407407407407


0.9907407407407407

In [23]:
(y_pred == y_test).mean()

0.9907407407407407

In [29]:
# 应用
comment = input('请输入您对本商品的评价：')
comment = [' '.join(jieba.cut(comment))]
print(comment)
X_try = vect.transform(comment)
y_pred = mlp.predict(X_try.toarray())
print(y_pred)

['一如既往 的 喜欢 ， 京东 价保 成功 ， 机器 完美 ！ 。 屏幕 音效 ： 立体 扬声器 绝对 完爆 其他 设备 。 外形 外观 ： 喜欢 黑 的 ， 很大 气 。 拍照 效果 ： 清晰 ！ 单 摄像 足够 ！']
[1]


## 朴素贝叶斯算法

In [30]:
# 朴素贝叶斯模型对比
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

nb_clf = MultinomialNB()
nb_clf.fit(X_train,y_train)

y_pred = nb_clf.predict(X_test)
print(y_pred)

from sklearn.metrics import accuracy_score
score = accuracy_score(y_pred, y_test)
print(score)

[1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 0 1 1 1 0 1 1 1 1 1 1 1 0 1 1 0 0 1 0 1 0
 1 1 0 1 0 0 1 1 1 0 1 1 0 1 0 1 1 1 0 0 1 1 1 1 1 0 1 1 0 1 1 0 1 1 1 0 1
 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1]
0.8888888888888888
